#!/bin/sh

WORK_DIR=/dev/shm
DOCKER_IMAGE=kiizawa/siriusdev
SINGULARITY_IMAGE=/dev/shm/siriusdev.img

export SINGULARITY_CACHEDIR=$WORK_DIR/cache
export SINGULARITY_TMPDIR=$WORK_DIR/tmp 
export SINGULARITY_LOCALCACHEDIR=$WORK_DIR/localcache

rm -rf $SINGULARITY_CACHEDIR; mkdir $SINGULARITY_CACHEDIR
rm -rf $SINGULARITY_TMPDIR; mkdir $SINGULARITY_TMPDIR
rm -rf $SINGULARITY_LOCALCACHEDIR; mkdir $SINGULARITY_LOCALCACHEDIR

singularity create $SINGULARITY_IMAGE
singularity build --writable $SINGULARITY_IMAGE docker://$DOCKER_IMAGE
